Improve error handling when parsing year directives
A literal Y directive or ‘year’ directive with an empty or invalid 
argument, e.g. ‘2o14’ (that is a small letter ‘oh’ instead of a zero)
would fail with the following rather unhelpful error message:
Error: bad lexical cast: source type value could not be interpreted as target