fileinfo_t: remove size member
it is currently not required but set. Incidentally, calling file_size()
on a bash pipe e.g. /proc/self/fd/11 fails with:

Error: boost::filesystem::file_size: Operation not permitted: "/proc/self/fd/11"

when executing ledger as

ledger -f <(cat journal)