fix macports dependencies on 10.14+
10.14+ does not support universal builds:

	Error: python27 cannot be installed for the configured universal_archs 'x86_64 i386' because the arch(s) 'i386' are not supported.

From https://trac.macports.org/ticket/57369#comment:6

	You just can't install ports universal on Mojave, so don't try to do so. Don't specify +universal on the command line